#!/bin/bash
echo Abriendo interficie para pruebas del judge
make clean
make
gnome-terminal --window -x ./Manager pworker pclient& 
sleep 1

gnome-terminal --window -x ./workerM localhost pworker localhost pworker0 &
#sleep 1
#gnome-terminal --window -x ./workerM localhost pworker localhost pworker1 &


